travis:
  secure:
    BINSTAR_TOKEN: nMvFowbDVic18vjobvtLzWBiI6yIJE59U2NlvAgAlXotdWr084zhc6/xhszFGw8yHffCvnm17D04D0skUivNt+FHBXPqlItTr9SUiZpCya3uJhcC4r9XNRYMi/a8LB33EVPeSTuhG/v/1OnNhjhXtjuHeRgB3me9KRC/HYNmQhAeQm351VYOwZY/Kq57cAqwMh76g3xASFqMoVEeeJoxQtWhpighWyxK6/4tOpxWg66LKWS67gcphwtKlAb1jJbXd9sF3Xk0Ni2g0Ea9sYyUZyo1VLh7i/yoIzzhIba/x2LiFpUpSL4X17+eE1EEy0atTTRFH6XsUJKRUc5k21kZZMhqz7Ak0GDV8x6ImLEwG2pf228LiMNfwN+UGDIkV+Qo8PsSPYKteDIx80c8ImGQWPYSUuLLyif9Skq/ZMp3+O2RMNAdoJiCkwmasqOCSgf7+OGVyoWJNCiBZw3N64lwK+YSeiwLxO1H7WRN/Wb2JNkorWtsYU1ulrhr9Sn2jsCGzIJr6SGVNDY+QUUZSzBJ7v2W4r5kgwY2wAVtrM+AGw2lJr4KeiKK7EUcHmsTL/gB00OPTj0eXpHyR0IpJp6nmiKg9VAE30Eu5UjmB/7gALE+I1ay3aqUdemxeKJYQk9GfVutO4nWiayyz++xDx4F6pNBLzhkwXeEI3qUzSCTQgk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
